-   id: check-branch-name
    name: Check branch name
    language: script
    entry: ./branch-name.sh
    always_run: true
    pass_filenames: false
    stages: [push]
-   id: check-commit-message
    name: Check commit message
    language: script
    entry: ./commit-message.sh
    always_run: true
    pass_filenames: false
    stages: [push]
